"use client";

import { Header } from "@/components/header";
import type { Metadata } from "next";
import { Saira } from "next/font/google";
import { ThemeProvider } from "styled-components";
import { defaultTheme } from "./theme";
import { GlobalStyle } from "./globals";
import { FilterContextProvider } from "@/context/filterContext";

const saira = Saira({
  weight: ["300", "400", "500", "600"],
  subsets: ["latin"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={saira.className}>
        <ThemeProvider theme={defaultTheme}>
          <GlobalStyle />

          <FilterContextProvider>
            <Header logoName="Capputeeno" />
            {children}
          </FilterContextProvider>

        </ThemeProvider>
      </body>
    </html>
  );
}
